### ISSUE TITLE
gsctl fails to run on alpine - user.Current() not implemented on linux/amd64

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#110]
### What did you do/observe?

```
$ gsctl --help
Could not get system user details using os/user.Current().
Without this information, gsctl cannot determine the user’s home directory and cannot set a configuration path.
Please get in touch with us via support@giantswarm.io, including information on your platform.
Thank you and sorry for the inconvenience!

panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/giantswarm/gsctl/config.init.1()
    /go/src/github.com/giantswarm/gsctl/config/config.go:93 +0x5bc
github.com/giantswarm/gsctl/config.init()
    /go/src/github.com/giantswarm/gsctl/config/config.go:302 +0x7b
github.com/giantswarm/gsctl/commands.init()
    /go/src/github.com/giantswarm/gsctl/commands/version.go:42 +0x9b
main.init()
    /go/src/github.com/giantswarm/gsctl/main.go:26 +0x58
```

### Details

- Operating system, platform/architecture:

```
$ uname -a
Linux 6dd830902cce 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 Linux
```

- Output of `gsctl version`: 0.6.3

- Any other details required to reproduce the problem:
  - Inside a Docker container.

**Comment by marians** [comment]
This also happens in a debian based Docker container.

```
$ gsctl
Could not get system user details using os/user.Current().
Without this information, gsctl cannot determine the user’s home directory and cannot set a configuration path.
Please get in touch with us via support@giantswarm.io, including information on your platform.
Thank you and sorry for the inconvenience!

panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/giantswarm/gsctl/config.init.1()
    /go/src/github.com/giantswarm/gsctl/config/config.go:93 +0x5bc
github.com/giantswarm/gsctl/config.init()
    /go/src/github.com/giantswarm/gsctl/config/config.go:302 +0x7b
github.com/giantswarm/gsctl/commands.init()
    /go/src/github.com/giantswarm/gsctl/commands/version.go:42 +0x9b
main.init()
    /go/src/github.com/giantswarm/gsctl/main.go:26 +0x58

$ uname -a
Linux 0613f7834bbb 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 GNU/Linux

$ cat /etc/debian_version
9.0
```

**Comment by marians** [comment]
[This article](https://stackoverflow.com/questions/29898620/user-current-not-implemented-on-linux-amd64-with-golang-using-docker-scrtach) points to the reason:

> The os/user package's user info lookup on Linux is implemented using the `getpwuid_r` system call, so will not work when compiled with `CGO_ENABLED=0`.

Interestingly this isn't a problem on Mac, Linux, or Windows. It only occurs inside a Docker container.

**Comment by hobti01** [comment]
Dockerfile to replicate the issue:
```
FROM debian:latest
ARG GSCTL_URL=https://downloads.giantswarm.io/gsctl/0.6.3/gsctl-0.6.3-linux-amd64.tar.gz
RUN apt-get -qq update && apt-get -qq install -y curl &&\
  curl -sSL $GSCTL_URL | tar xz --strip=1 &&\
  chmod +x gsctl && mv gsctl /usr/local/bin/
CMD /usr/local/bin/gsctl
```

Replication:
```
docker build -t gsctl .
docker run -it gsctl
Could not get system user details using os/user.Current().
Without this information, gsctl cannot determine the user's home directory and cannot set a configuration path.
Please get in touch with us via support@giantswarm.io, including information on your platform.
Thank you and sorry for the inconvenience!

panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/giantswarm/gsctl/config.init.1()
	/go/src/github.com/giantswarm/gsctl/config/config.go:93 +0x5bc
github.com/giantswarm/gsctl/config.init()
	/go/src/github.com/giantswarm/gsctl/config/config.go:302 +0x7b
github.com/giantswarm/gsctl/commands.init()
	/go/src/github.com/giantswarm/gsctl/commands/version.go:42 +0x9b
main.init()
	/go/src/github.com/giantswarm/gsctl/main.go:26 +0x58
```
