### ISSUE TITLE
segmentation violation in 'list releases' when server not reachable

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#181]
### What did you do/observe?

I had localhost:9000 set as endpoint, but no API server running, and got this when running `gsctl list releases`:

```nohighlight
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1372eae]

goroutine 1 [running]:
github.com/giantswarm/gsctl/commands.listReleases(0xc420013240, 0x15, 0xc420014270, 0x24, 0x0, 0x0, 0x169ba60, 0x1754000, 0x0)
	/go/src/github.com/giantswarm/gsctl/commands/list_releases.go:210 +0x63e
github.com/giantswarm/gsctl/commands.listReleasesOutput(0x1695880, 0x16ba820, 0x0, 0x0)
	/go/src/github.com/giantswarm/gsctl/commands/list_releases.go:122 +0x5f
github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra.(*Command).execute(0x1695880, 0x16ba820, 0x0, 0x0, 0x1695880, 0x16ba820)
	/go/src/github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra/command.go:746 +0x2e7
github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1693900, 0x144f689, 0x3, 0x0)
	/go/src/github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra/command.go:827 +0x30e
github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x1693900, 0xc420043f70, 0x138052d)
	/go/src/github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra/command.go:780 +0x2b
main.main()
	/go/src/github.com/giantswarm/gsctl/main.go:24 +0x2d
```

### What did you expect?

Releases output (some empty state)

### Details

- Operating system, platform/architecture: Mac OS 10.13.2

- Output of `gsctl version`:

```
Version:     0.9.2
Build date:  2017-12-07T09:15:51Z
```
- Any other details required to reproduce the problem:

    API endpoint: http://localhost:9000

**Comment by marians** [comment]
We should be able to use the behaviour from https://github.com/giantswarm/gsctl/pull/194 for this fix. Probably in general, not just for one more command.

**Comment by marians** [comment]
No longer happening, it seems. Added a test in #210.
